### PR TITLE
SPM Support

### PR DESCRIPTION
**Pull request by MadGeorge**
Hello! Thank you for the service and this SDK. We are enjoying be clients of yours. 
Iterate SDK almost satisfies our needs at the moment, but at the same time, it's one of the few dependencies which are not support Swift Package Manager, which prevents our goal to migrate from CocoaPods. 
So this is our contribution to speedup this improvement to be happens. 

I'm very happy to say that very minor changes were need to add SPM support.  
The main challenge was to support storyboard resource in both CocoaPods and SPM builds. In order to do this option "Inherit Module From Target" should be disabled for all views with custom classes in the storyboard and xib files. 

The only bad news is we can not use `swift-tools-version` bellow 5.4 since we need `Bundle.module` which was not available earlier. 

Additionally, in order to full work, release management of this repository is required. In short, release tags naming should be changed to standardized [semantic versioning](https://semver.org/) without "v" prefix. 

I'm able manually test very few cases used in our app. I hope you can help with full testing to confirm nothing was broken especially when CocoaPods is used. 
For some strange reason i'm not able to download iOS Simulator 12.0, so the minimum version was tested is 13.4.
Units tests are passed successfully, which is not a surprise. 

---
Addressing issue https://github.com/iteratehq/iterate-ios/issues/66

### CODE REVIEW

**Comment by MadGeorge** [comment]
Hello. Requesting a review.
@lankybutmacho @msingleton

**Comment by ZevEisenberg** [comment]
bump - any chance of this getting merged?

**Comment by msingleton** [comment]
@MadGeorge @ZevEisenberg Merged! Apologies for the long delay and thanks for the contribution @MadGeorge

**Comment by msingleton** [comment]
@MadGeorge no problem, we tested the cocoapod and carthage install, only thing we needed to do was change the target name to `Iterate` which we prefer anyway so that worked out

**Pull request merged**
